### PR TITLE
PHPCS: document run parameters in project ruleset

### PR DESCRIPTION
**Pull request by jrfnl**
This makes it easier for contributors to run the PHPCS command for the project.

Includes:
* Adding the `Tests` directory to the run - excluding the test case files in `fixtures`.
* Cleaning up the result report by using the `basepath` configuration.
* Making the run faster by using `parallel` scanning if available,

### CODE REVIEW

**Comment by sirbrillig** [comment]
Nice! I didn't know about those options. Thank you.

**Comment by sirbrillig** [comment]
Hm... I just got the CI tests to run on contributor PRs and this one fails for php7 with

> Script ./vendor/bin/phpcs --standard=./VariableAnalysis handling the lint-self event returned with error code 3

**Comment by jrfnl** [comment]
> Hm... I just got the CI tests to run on contributor PRs and this one fails for php7 with

Hang on, yes, that's my bad, though probably fails on PHP 5 too, but may do silently.

There are two ways to solve this, but I need some input to know which o use:

1. The `lint-self` command doesn't use the `phpcs.xml.dist` file, but points to a standard, so I could add the command line arguments back.
2. I could remove the `lint-self` command and just add the `VariableAnalysis` standard to the `phpcs.xml.dist` file. That way there will be only one PHPCS run which does everything in one go.

@sirbrillig Have you got a preference ? I'd recommend option 2.

**Comment by jrfnl** [comment]
I've added a second commit implement option 2 for now. Let me know what you think.

**Comment by sirbrillig** [comment]
Oh, cool. I didn't know you could do that. I like option 2. Thanks!

**Comment by jrfnl** [comment]
> Oh, cool. I didn't know you could do that. I like option 2. Thanks! 

Well, as the DealerDirect plugin registers the standard with PHPCS correctly, it's available, so yes, it can be added to the ruleset ;-)

**Pull request merged**
