### PR TITLE
Add arrow function support

### LINKED ISSUE #134: Add support for PHP 7.4 arrow functions
PHP 7.4 introduces arrow functions. It would be great if this library would add support for these.

```php
// Currently throwing false positives for undefined variables $a x 2, $b x 2, $c x 1.
$fn = fn($a, $b, $c) => $a + $b; // Unused $c (false negative).

function foo() {
    $a = 120;

	// Currently throwing false positive for undefined variable $b x 2.
    $fn1 = fn($b) => $a + $b;

	// Currently throwing false positive for undefined variable $b.
    $fn2 = fn($b) => $a; // Unused $b (false negative).

	// Currently throwing false positive for undefined variable $b x 2, $c x 1.
    $fn3 = fn($b) => $b + $c; // Undefined $c (false negative). Unused variable $fn3 (correctly thrown).
    
    var_dump( $fn1(10) );
    var_dump( $fn2(10) );
}

```

Note: PHPCS itself doesn't properly support arrow functions until PHPCS 3.5.5 (not yet released).
If continued support for older PHPCS versions is desired, you may want to look at the `PHPCSUtils` `FunctionDeclarations::isArrowFunction()` and `FunctionDeclarations::getArrowFunctionOpenClose()` methods.

Refs:
* https://wiki.php.net/rfc/arrow_functions_v2
* https://github.com/squizlabs/php_codesniffer/issues/2523

### PR DESCRIPTION
**Pull request by sirbrillig**
Fixes #134

### CODE REVIEW

**Comment by sirbrillig** [comment]
The problem I'm running into is that I don't know how to find out where the scope ends for an arrow function. PHPCS doesn't seem to consider it a scope at all:

```
        Process token 55 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 56 on line 9 [opener:49;]: T_FN => fn
        Process token 57 on line 9 [opener:49;]: T_OPEN_PARENTHESIS => (
        Process token 58 on line 9 [opener:49;]: T_VARIABLE => $foo
        Process token 59 on line 9 [opener:49;]: T_CLOSE_PARENTHESIS => )
        Process token 60 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 61 on line 9 [opener:49;]: T_DOUBLE_ARROW => =>
        Process token 62 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 63 on line 9 [opener:49;]: T_VARIABLE => $foo
        Process token 64 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 65 on line 9 [opener:49;]: T_STRING_CONCAT => .
        Process token 66 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 67 on line 9 [opener:49;]: T_VARIABLE => $bar
        Process token 68 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 69 on line 9 [opener:49;]: T_STRING_CONCAT => .
        Process token 70 on line 9 [opener:49;]: T_WHITESPACE => ·
        Process token 71 on line 9 [opener:49;]: T_VARIABLE => $subject
        Process token 72 on line 9 [opener:49;]: T_SEMICOLON => ;
        Process token 73 on line 9 [opener:49;]: T_WHITESPACE => ·
```

However, variables defined inside the arguments list for the function (`$foo` in the above example) do not exist outside of the arrow function.

There's no obvious token to use to find the end to an arrow function; it's the end of the expression but I'm not sure of an easy way to find that.

**Comment by sirbrillig** [comment]
Ah, I was wrong, there's additional processing done to find the arrow function scope:

```
        => token 459 on line 57 processed as arrow function
                * scope opener set to 464 *
                * scope closer set to 467 *
                * parenthesis opener set to 460 *
                * parenthesis closer set to 462 *
                * token 464 on line 57 changed from T_DOUBLE_ARROW to T_FN_ARROW
        * token 448 on line 56 changed from T_OPEN_SQUARE_BRACKET to T_OPEN_SHORT_ARRAY
        * token 449 on line 56 changed from T_CLOSE_SQUARE_BRACKET to T_CLOSE_SHORT_ARRAY
```

**Comment by jrfnl** [comment]
@sirbrillig Arrow function support in PHPCS was only added in PHPCS 3.5.3 and was pretty broken until 3.5.5 and there are still bugs being found.

As PHPCS 3.1 is your minimum, you will need to sniff for both `T_STRING` as well as `T_FN` tokens.

The PHPCSUtils [`Collections::arrowFunctionTokensBC()`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Tokens-Collections.html#method_arrowFunctionTokensBC), [`FunctionDeclarations::isArrowFunction()`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-FunctionDeclarations.html#method_isArrowFunction) and the [`FunctionDeclarations::getArrowFunctionOpenClose()`](https://phpcsutils.com/phpdoc/classes/PHPCSUtils-Utils-FunctionDeclarations.html#method_getArrowFunctionOpenClose) methods can help you handle all this in a PHP cross-version manner.

Caveat: that is: in so far as possible of course, as when PHPCS sets the wrong `scope_opener` somewhere making all `scope_opener`s after that for the rest of the file be off, that's not something PHPCSUtils can conceivably correct for.

**Comment by jrfnl** [comment]
Just noticed that you are changing the minimum PHPCS version to `3.5` in this PR ;-) Even so, that still won't solve the issue as, as I mention before, arrow function support is basically broken until `master`.

**Comment by sirbrillig** [comment]
I'm just experimenting so far. I've got it to recognize the scope of variables defined within an arrow function. Now I just need to get it to properly scan the variables within that scope at scope close. The tricky thing is that variables in the scope _also_ include variables from the parent scope.

**Comment by sirbrillig** [comment]
Hey! We're getting there! I got stuck because there's a bunch of old poorly-named, poorly-documented code lying around that I've been meaning to refactor for a long time. I spent a few days tearing the scope detection apart and then re-building it from scratch and I think it works much better now. I need to rebase this PR to make some of the commits make sense, but I'll wait till this is all done.

Now just to support PHP 5.6...

**Comment by sirbrillig** [comment]
💥 🥳 💥

**Comment by sirbrillig** [comment]
> Arrow function support in PHPCS was only added in PHPCS 3.5.3 and was pretty broken until 3.5.5 and there are still bugs being found.

Coming back around to this, since we rely on `scope_opener`, `scope_closer`, and `conditions` from a `T_FN` token, if we can't trust them we'll need to use your work-arounds. I'll see what I can do.

**Pull request merged**
